module.exports = {
    angry : " на",
    baka : "",
    bite : "",
    blush : "",
    bored : " по",
    cheek : "",
    cry : " из-за",
    cuddle : "",
    dance : " с",
    drink : " с",
    feed : "",
    hate : "",
    hug : "",
    kill : "",
    kiss : "",
    laugh : " над",
    lewd : "",
    lick : "",
    love : "",
    nuzzle : "",
    pat : "",
    poke : "",
    pout : " на",
    sad : " из-за",
    slap : "",
    sleep : " с",
    wait : "",
}